name: publish-bbb
on:
  workflow_run:
    workflows: ["test-bbb"]
    branches: [main]
    types:
      - completed
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "publish-bbb ok"