name: test-bbb
on:
  push:
    branches:
      - main
    paths:
      - "packages/bbb/**"
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: echo "test-bbb ok"
